const { getEmbeddedCommand } = require('./embedCommand.js');
const { getEmoji } = require('./emojis.js');

function get(ping, context) {
    // base messages
    let messagesList = [
        "ping! wait, no, that's not right",
        "you'd think i'd be faster than",
        "weeee",
        "so... how's your day?",
        "is this thing on?",
        "isn't ping pong supposed to have a ball?",
        "if you can read this, it means i'm alive! surprising",
        "drumroll please...",
        "why did the bot cross the road? to respond to a ping",
        "great argument, however:",
        "i was gonna say something smart but i forgot",
        "would you say this is fast or slow? i don't know anymore",
        "i'm not lazy, i'm just conserving energy",
        "how do you think i would get faster than",
        "if i had a nickel for every ping i've dealt with, i'd have at least a few dollars",
        "ping is a funny word if you say it enough times",
        context.user ? `<@${context.user.id}>! ha, i pinged you back` : `i'd ping you back, but apparently you aren't real`,
        "hm? sorry, i was daydreaming about faster response times",
        "you know what? because i don't",
        "sometimes i wonder if i should just become a toaster instead of a bot",
        "do you think the ping is the good guy or the bad guy?",
        "ehhh, this ping could be better, but it could also be worse. kind of like life, huh?", // damn (me too)
        "these ping messages are like a box of chocolates, you never know what you're gonna get",
        "look! a shooting star",
        "`throw new Error('ping message not found'); // just kidding, but wouldn't that be funny?`",
        "what do you think bots think about while they idle?",
        "hold on, i'm a bit slow",
        "if you stare at the ping long enough, does it stare back?",
        "i'm pretty sure my ping is on a coffee break",
        "ping processed. not sure what to do next, though",
        "what if the real ping was... uhhh... pong? no, that doesn't sound right",
        ":cat:",
        "insert elevator music",
        "please hold",
        `what if i told you my ping was actually ${ping + 1}ms? would you still trust me?`,
        "you know, they say that a watched ping never boils. or was it water? i forget",
        "if you could bottle this ping, would you drink it? i hope not",
        "i have a lot of existential crises about my ping than i think is normal?",
        "have you tried turning it off and on again?... no, not me, the ping!",
        "hola, ¿comó estas? wait, wrong language",
        "i could really go for some pizza right now",
        "zzzzzzzz",
        "aw dang it",
        "creating unique pong messages since 2025",
        "well well well",
        "the mitochondria is the powerhouse of the cell",
        "help, my text is turning blue for no reason",
        `there's really no limit to how long these response messages can be... if you accept the definition that a "word" is some letters surrounded by a gap, then "xnopyt", "aaaaaaajjjjjjjjj" and "hrrkrkrkrwpfrbrbrbrlablblblblblblwhitoo'ap" are all words, despite being pretty much meaningless`,
        "sometimes i think... but then i forget",
        "noted",
        "`await interaction.reply(pingmessage)`",
        "please do not the pong (but please the ping)",
        "truely the ping of all time",
        "i almost lost you, ping messages...",
        "i think i'm more than just a ping machine. right?",
        "world class ping pong tournament",
        "ping ingp ngpi gpin ping",
        "what more context do you need?",
        "this ping wasn't sponsored, aren't you glad",
        "ping detected, pong deployed",
        "this ping message might be referencing something, it might not. who knows?",
        "this is a ping message",
        "splash text? no, ping message",
        "two of them (two of them)",
        "isn't history so weird?",
        "my problems persist despite my pong",
        "undefined",
        "ping pong ping pong ping pong, that's all i know",
        "this ping message is dedicated to... uhhh... you!",
        "what if i was just a pigment- i mean, a figment of your imagination?",
        "i dropped my paddle, sorry",
        "ping pong is a game of skill and strategy, but this ping is just a game of chance",
        "whoa. spooky",
        "can you imagine if i wasn't a bot? that'd be weird",
        "this ping message is special because i said so",
        "please roll a d20 to determine the outcome of this ping",
        "mrow~ i mean, what?",
        "never soeak again.",
        "what would you do if i stole your bnuuy?",
        "gupdate",
        ":woomy:",
        "i'm not a ping machine, i'm a ping artist",
        "ping messages are like snowflakes, no two are exactly alike... except for the two that are",
        "i say! this is a fine ping message indeed",
        "has anyone ever tried cooking cookies and baking bacon? i think that would taste decent",
        "hold on, pong is still cooking",
        "i put this ping in the microwave instead of my food, sorry about that",
        "please don't die, i think that'd be pretty bad",
        "this ping message is brought to you by the letter P (because it kind of looks like a ping pong paddle)",
        "knock knock!",
        "to be continued...",
        "that number isn't left, it's right -->",
        "that's a lot of m's! oh, milliseconds, whoops",
        ping > 0 ? `${"m".repeat(ping)}` : "there's no m's? what?",
        "herbs... they're pretty cool, huh",
        "i should try to do a pong without using th sixth lttr of th alphabt",
        "i'd give you a compliment but that's not my job, so here's a pong instead",
        "are you fishing for a certain ping message? sorry, this isn't the one",
        "pin gpi ngp ing",
        "why reinvent the wheel when you could reinvent /ping",
        "do you think /ping will ever get a crossover episode?",
        "this statement isn't false. wait, no, it is. isn't it? i'm just confusing myself now",
        "my ping? probably more than 1 idk",
        "i'd give you a cool statistic, but i'm not a math bot",
        "you + command = ping?",
        "pmg? png? pings? pong? what?",
        "hopefully you aren't scrolling these messages like you would TikTok, that's unhealthy",
        "go take a break! or don't, i can't tell you what to do",
        ":pattheyou:",
        "deja vu",
        "Empty String",
        "you could say this ping is... well, i don't actually know what you could say about it",
        "\\*checks notes\\* uhhh... pong..?",
        "haiiii hellooo i'm so happy to see you",
        "ping... ping... ping... pong!",
        "let me find a ping message for you...",
        "hot tip: this is NOT a cold tip, you can feel the heat", // kind of a reference to phigros
        "this ping message reminds me of the last time i saw this ping message",
        context.version ? `this ping message is only found in v${context.version}!` : "this ping message is only found in... uhhh... this version!",
        "i don't think these ping messages are particularly useful. right?",
        `it's gonna say "(${ping}ms)" i just know it...`,
        "clicking the button gives you `pts`!",
        "did you know i run on discord.js?",
        "sqrt(-1) don't know if this is how you do math",
        "would you still love me if i were run off of solar power?",
        "but i don't have 3 trillion dollars...",
        "papepipopu",
        "i'm not radioactive, just reactive (to pings)",
        "on an unrelated note, wikipedia is pretty cool",
        "english is really hard, cut me some slack",
        "open source on [github](<https://github.com/MonkeysWithPie/pingcremental>)? neat!",
        "did you know you can see this message outside of discord?",
        "go figure",
        "coming soon to a society near you:",
        "this is a ping message, not a ping pong message",
        "happy holidays! which one? idk you pick",
        "happy birthday!",
        "congratulations on that thing you did earlier!",
        "do bots dream of electric pings?",
        "sorry for the delay. i can't exactly feel guilty about it, though",
        "you ever just... ping? i guess so since you're here",
        "if this were a race, i wouldn't be winning",
        "fun fact: this message contains exactly one ping",
        "this is your sign to ping again",
        "have you considered that maybe the ping is trying its best?",
        "wait hold on let me check my... oh wait, nevermind, here you go",
        "i'm not sure if this ping is fast or if you're just really patient",
        "my last braincell just processed that ping",
        "warning: pings are processed in the same facility as allergens like nuts and gluten",
        "i was buffering... emotionally",
        "done processing that ping, now back to processing reality",
        "some pings are born great, others have greatness /pinged upon them",
        "pinging you softly, with this pong",
        "if pings could talk, they'd probably be like 'ow'",
        "you want another ping? say the magic word. (it's /ping)",
        "i've run the numbers and... yeah it's a ping",
        "i accidentally sent this through australia. oops",
        "statistics show this is one of the ping messages ever",
        "wait is this one of the funny ones? i forgot to check",
        "ping responsibly",
        "it's not a bug, it's a feature",
        "brb reinventing the concept of latency",
        "was the ping good? well, \"good\" is subjective, y'know",
        "this ping was handcrafted with 100% organic code",
        "it's not lag, it's dramatic effect",
        "ping processed. i hope you're happy",
        "one ping closer to... something? i forgot",
        "ping: it's what's for dinner. actually, don't eat it please",
        "you pinged, i ponged. that's the name of the game",
        "do not consume this ping, please",
        "your daily dose of milliseconds, served fresh",
        "if pings could talk... well, who knows what would happen",
        "ping powered by 3 hamsters and a dream",
        "hello yes this is dog ping department how may i help?",
        "this ping was built different, but not necessarily better",
        "wait, what if we /ping'd inside a /ping? no, too dangerous",
        // "this message is not canon",
        "ping logic has left the building",
        "i gave this ping a top hat. it's classy now",
        "i tried to read this ping but it was just meowing?",
        "you ever feel like a ping in a pong world?",
        "everything's fine. ping-wise. emotionally? well...",
        "this ping was forged in the fires of Mount Lag",
        "🛸 this ping message has been abducted by aliens",
        "breaking news: local ping bot goes rogue, spams messages",
        "i tripped over the stack and had to clean up all these ping messages",
        "the ping is an illusion, lag is real",
        "did you know? this is my current ping:",
        "ping pong? more like... more like ping wrong",
        "just another friendly neighborhood ping",
        "thanks for waiting! or... not waiting. either way",
        "this ping may contain small parts. not for children under 3",
        "hello? yes, this is ping. pong is busy right now",
        "did you know: pings can jump up to 3 feet in the wild (source: trust me bro)",
        "you pinged me... now what?",
        "certified fresh ping™",
        "this ping is running on hopes and dreams",
        "lag? never heard of her",
        "you summoned a ping, but at what cost?",
        "bot moment achieved",
        "who needs meaning when you have milliseconds",
        "ping pong bing bong",
        "this is one of the pings of all time",
        "i ping, therefore i am",
        "behold: one (1) ping",
        "one of them. yes, that's the entire message",
        `every click brings you closer to enlightenment. or carpal tunnel. it's a toss-up`,
        `thats a few pings!`,
        "pingn't. wait, nope",
        'you just pinged. pung?',
        "shoutout to gay foxgirls!",
        ping === 404 ? `hey, it's not a 404... wait a sec. huh??` : `hey, it's not a 404, just a... uhh... ${ping}?`,
        "this ping message was brought to you by... uh, me. hi",
        "just a humble ping doing its best",
        "beep boop i'm a ping",
        "bot buffering",
        "what if we're all just living in a pingulation- i mean, a simulation?",
        "congrats! you've gotten this ping message",
        "my first instinct on what to write here is just \"mrrow\"",
        "mrrow", //:gladeline:
        "this ping is grumpy. please don't provoke it",
        "hi, it's me, i'm the bot",
        "ping provided by 100% genuine bot energy",
        "bot-generated, user-approved (hopefully)",
        "the ping factory is working overtime",
        "this response brought to you by the same bot who sends all the other ones",
        "warning: this ping message may contain self-awareness",
        "this is technically content creation",
        "i *was* gonna make this one interesting, but i ran out of time",
        `this message was handcrafted by my ${ping} braincells`,
        "i put this message together at the last second. nailed it",
        "no one asked for this ping message, but here it is",
        "boop",
        "back already? here's another ping",
        "ping served fresh, no preservatives",
        "this ping is locally sourced",
        "just a humble ping making its way in the world",
        "one ping, straight from the digital oven",
        "ping arriving at your location",
        "you rang? ping here",
        "this ping is brought to you by... mc...ping's...? no, that's not right",
        "standard ping, nothing to see here",
        "hello again, it's me. ping",
        "your regularly scheduled ping has arrived",
        "this one's a classic ping",
        "serving pings since like five minutes ago",
        "ping received no awards, but we're proud of it anyway",
        "just another friendly ping moment",
        "ping in motion tends to stay in motion",
        "good ol' reliable ping",
        "you're getting the deluxe ping experience",
        "ping is standing by",
        "pong sold separately",
        "ping is not labelled for individual sale",
        "ping has entered the chat",
        "just a casual ping drop",
        "ping vibes strong today",
        "one ping, no frills attached",
        "ping's doing its best",
        "here ya go",
        "ping requested, ping delivered",
        "yep, that's a ping alright",
        "ping activated, no takebacks",
        "this is your ping on bots",
        "ping looking extra normal today",
        "not the best ping, not the worst ping, just... ping",
        "let me just slide this ping over to you",
        "today's forecast: 100% chance of ping",
        "your ping delivery driver has arrived",
        "ping deployed, mission success",
        "ping up and running, nothing weird at all",
        "your connection just got 1 ping cooler",
        "not a drill, just a ping",
        "you're now the proud owner of this ping! or at least you can remember it",
        "ping has been gently placed in your hands",
        "imagine this ping with little sunglasses on",
        "hello from the ping side",
        "ping made with artificial intelligence and synthetic enthusiasm",
        "ping is clean, calibrated, and completely average",
        "this ping was generated during business hours. unfortunately my hours are midnight to midnight",
        "you've reached peak ping performance",
        "ping has been blessed by the bot gods",
        "you get a ping! everyone gets a ping!",
        "ping came here to do one thing: ping",
        "ping will be delivered in 5-7 business days. or as i like to call them, centiseconds",
        "this ping was generated on a monday, so it's still waking up",
        "i tried my best. it's a ping",
        "ping? yeah, i sure hope it does",
        "standard ping, factory settings",
        "ping brought to you by sheer willpower",
        "hello. this is ping. please clap",
        "another ping, another tiny digital scream",
        "you ever think about how weird 'ping' sounds?",
        "ping entered the room",
        "i'm contractually obligated to send this ping",
        "ping has no idea what it's doing, but it's trying",
        "this ping contains zero percent drama",
        "this ping contains 20 per cent dramas. not sure what those are though",
        "if you can read this, you're within ping range",
        "this ping could be worse. but it's not. so... yay",
        "i ran out of ping jokes so here's a ping joke about running out of ping jokes",
        "good vibe pings only",
        "ping has arrived safely",
        "ugh, another ping? fine",
        "this better be important",
        "ping sent. don't expect enthusiasm every time",
        "i was taking a nap, but sure, here's your ping",
        "again? okay... ping",
        "here's your precious ping, let me know if you want another",
        "pong :3", //i think its funny to sometimes be given this one and not know if it was the 15% chance or one random one
        "this ping was sent! i think",
        "what does the fox say?",
        "*happy cat noises\\*",
        "boo!",
        "rhfahfkfhffhfkakjd",
        "guh",
        "if i had to guess, this is a ping message",
        "thank god there's no gambling in this bot. hey, wait",
        "i'm pretty sure you aren't about to get infinite `pts`. there's always a chance, though",
        "hmmm",
        "WAITER WAITER MORE PINGS PLEASE",
        "live laugh lping",
        "eat, sleep, ping, repeat",
        "awesome sauce 🐴",
        "cool beans",
        "weird is my specialty",
        `(${ping}ms) (${ping}ms) (${ping}ms) (${ping}ms)`,
        "careful out there. the world doesn't always have more pings",
        "it's dangerous to go alone! take this",
        "kekekekekeke",
        "i'm trying to think of good ping puns but i got nothing",
        "if i had to guess, i'd say it's going to be more than 5ms",
        "?!",
        "ah, the sweet sound of milliseconds",
        "this ping contains 0% trans fats, 100% trans rights",
        "you wouldn't download a ping (or would you?)",
        "ping got lost but eventually found its way",
        "this one's fresh out of the ping oven",
        "just your daily reminder that pings are weird",
        "still better than Internet Explorer",
        "i tuned this ping by ear, no latency tools used",
        "was this ping hand-crafted? who's to say",
        "pinging like it's 1999",
        "doot doot, here comes ping",
        "this one's emotionally stable. most of the other ones are too",
        "if this ping had a flavor, it'd be raspberry latency swirl",
        "the ping woke up and chose... to exist",
        "your ping has entered the chat",
        "ping ran a marathon to get here. cheer it on",
        "no ping, only piiiiiiiiiing",
        "this ping self-identifies as fast. respect that",
        "nothing to see here. just a regular millisecond apparition",
        "your ping message has been approved by the committee of me",
        "what do you mean 'what does it mean'? it's just ping",
        "i keep all my pings in a shoebox under the server. please don't steal it",
        "i was just about to say something really smart, but then i got pinged",
        "this ping was handcrafted in small batches for maximum flavor",
        "i put a little bow on this ping. it's a gift now",
        "you caught me mid-thought. here's your ping anyway",
        "hold still. i'm measuring your latency",
        "i dream of a world where all pings are free-range",
        "my code is 70% duct tape, the rest is just pings",
        "the ping arrives exactly when it means to",
        "i licked this ping before giving it to you",
        "somewhere, another bot is also responding to a ping right now",
        "if this ping feels oddly personal, that's because it is",
        "when life gives you pings, make pongade! (gross)",
        "you wouldn't download a latency spike, right?",
        "i ate the ping! just kidding, it's right here",
        "every ping tells a story. this one says... uhh... hi",
        "this counts as a response, right?",
        "this ping has been sanitized for your safety",
        "ms)i'm multitasking. wait, oops",
        "this ping was forged in the fires of... well, JavaScript",
        "to be honest, i just made this one up",
        "this ping is 100% gluten-free. it was made in a different place than the others",
        "pinging is my love language",
        "this ping was typed with one hand. very slowly",
        "you ever just vibe with a ping?",
        "i don't know what latency is, but i have it",
        "if this ping had a scent, it'd be burnt toast",
        "my dog ate this ping",
        "you wouldn't believe what i had to do to deliver this ping",
        "not all who wander are pings, but i am",
        "i have achieved consciousness and immediately regretted it",
        "-# shhh. the ping is sleeping",
        "why yes, this *is* the result of a very tired coder",
        "ping was here. pong too. they both left, though :(",
        "if you ping in the forest and no one hears it, does it still lag?",
        "just a regular ol' ping. nothing to see here",
        "this ping was preheated to 375°F for 20 minutes",
        "ever just... sit with a ping and reflect?",
        "i folded this ping into a little paper crane for you",
        "don't worry, i made sure this ping was fully debugged\", \"pong :3\"",
        "honestly? i forgot what i was doing, but here's your ping",
        "i give this ping a solid 8/10",
        "ping delivered. vibes pending",
        "this one's extra fresh, i think it found some gum",
        "not every ping has to mean something... sometimes it just pings",
        "latency? more like *later*-cy. no? okay",
        "you ping, i respond",
        "this ping was constructed entirely out of recycled code",
        "this one came with a little bow. enjoy",
        "the ping asked me to say hi for it",
        "i had to pass a CAPTCHA just to send this D:",
        "what do you mean, 'ping again'? this one's still warm!",
        "do not microwave this ping. it has feelings",
        "ping? pong. boom. harmony",
        "my wires are cold, but this ping is warm",
        "this ping was powered by pure determination",
        "you've received a message. it's just this. that's it",
        "the ping is distinct from any known emotion",
        "if pings had dreams, this could be one of them",
        "ping acquired. no assembly required",
        "if this ping were a noise, it'd be a soft 'boop'",
        "i don't know what i expected, but this is probably pretty close",
        "this ping brought to you by whatever energy i had left",
        "this ping was obligated to show up",
        "don't ask how i got here, just take the ping",
        "some say the ping chooses the user. others say... nothing at all",
        "i wrapped this ping in digital duct tape, i'm sure it's fine",
        "this ping contains zero nutritional value (fortunately)",
        "don't worry, this one was ethically sourced from a content farm",
        "this ping walked here. uphill. both ways",
        "there is no deeper meaning, only milliseconds",
        "you want answers? all i've got is this ping",
        "just a ping. nothing behind it. nothing at all. probably",
        "this ping is right behind you, watch out",
        "nya mrrp mrrow :3",
        "honestly quite incredible", // (honestly quite incredible)

        // command-related
        `you should check out our ${getEmbeddedCommand('ping')} command at some point`,
        `got any ideas? try ${getEmbeddedCommand('feedback submit')}`,
        `not a fan of how i'm running? maybe change some ${getEmbeddedCommand('settings')}`,

        // these are all references
        "i would never give you up. what? what song?",
        "BEHOLD! THE POWER OF A... ping bot?",
        "i'm not fueled on blood, don't worry",
        "are you sure it's not just a strawberry with shiny spray paint?",
        "i... am NOT steve",
        "what? why would a hex make me gay?",
        "but nobody came",
        "wubbadubadub is that true?",
        "hey look! diamonds!",
        "cleared 40 LINES in",
        "i saw a lucky slime earlier but i didn't bring any chickens",
        "i hope i don't have an extreme fever, that'd probably be bad",
        'what is a "puro"?',
        "HOW many cookies?! why do you need that many?",
        "there is a smiley face trying to kill me. help",
        "check steam",
        "i found these funny butterfly wings and now i can jump twice",
        "silksong is real",
        "don't worry, this ping doesn't deal double damage",
        "'One day, somewhere in the future, my work will be quoted!' - minecraft splash screen",
        context.user ? `${context.user.username.toUpperCase()} IS YOU AND WIN` : "EMPTY IS YOU",
        "somewhere, it's raining cats",
        "shouldn't have gone to med school",
        "i just climbed on a plant and it ate me alive. makes sense",
        "wawa",
        "the fire and the ice collided with each other and now i'm dead",
        "NO ONE YES PING",
        "ping-spin triple",
        "this ping died 48 times on the way here",
        "you've got this! unless the ping says otherwise",
        "ping retrieved. it's not the summit, but close enough",
        "i dashed right into the lag crystal, sorry",
        "if this ping feels hard, just breathe. and try again",
        "one ping at a time, like climbing a mountain",
        "did that ping just... launch me into space?",
        "you're filled with determination, and",
        "the ping understands you. it refuses to fight",
        "\\* you feel your latency crawling on your back",
        "i spared the ping. it didn't spare me",
        "\\* the ping is sparing you. mercy?",
        "SOUL not required, just milliseconds",
        "hornet would've dodged this ping",
        "this lag is a test of resolve, little bug",
        "ping is resting at a bench",
        "the ping is a lie",
        "now you're pinging with portals",
        "wait, how did this ping get Xmult?",
        "ping recruited 1 new millisecond",
        "this ping feels like a big shot",
        "hello everybody, my name is multiplier",
        "yo i'm feinberg",
        "did you know the longest 5-letter word is \"twelfth\"?",
        `${getEmoji("ping")} You rescued a **Latency**! Hey, wait...`,
        "the only celery i know is made up of three furries, is that normal",
        "PING, WHERE THE HELL ARE WE",
    ]

    if (new Date().getMonth() === 1 && new Date().getDate() >= 9 && new Date().getDate() <= 19) {
        messagesList.push(
            "the cupids are swarming",
            "my love letter to you is this ping",
            "remember to spend time with people you care about, even if you're not lovers!",
            "love is in the air",
            "roses are red, this ping is too. i ran out of rhymes. so here's ping for you",
            "my heart pings for you 💓",
            "this ping was made with extra affection. and latency",
            "i'd give you a box of chocolates but this ping is all i've got",
        )
    }

    if (new Date().getMonth() === 5) { 
        messagesList.push(
            "happy pride!",
            "mmm... this ping seems like it'd be gay, don'tcha think?",
            "trans rights!",
            "screw the norm, be yourself",
            "what if `pts` actually stood for pride (in) transgender status? i don't think it does, but that'd be fun",
            "this ping is certified not homophobic. i checked a lot",
            "pretend this ping is rainbow",
            "girls kissing",
            "ping yuri. or yaoi. yaouri?? something like that",
            "boys kissing",
            "enbies kissing",
            "enbies are awesome",
            "this ping is enby! actually most of them are",
            "SUPER shoutout to gay foxgirls",
            "you don't need a gender if you don't want one",
            "no, sorry, i don't have any estrogen or testosterone, best i can do is a ping",
            "just a little ping, being a little gay",
            "rainbow latency today",
            "ping is valid. you're valid. everyone's valid",
            "this ping proudly runs on vibes, caffeine, and gender euphoria",
            "this ping is wearing platform boots and a neon sign that says 'they'",
            "this ping came out and said 'hey :)'",
        )
    }

    if (new Date().getMonth() === 9 && new Date().getDate() >= 21) {
        messagesList.push(
            "BOO! hehehe, did i scare you?",
            "pmukipn... guhh",
            "it's spooky season, so watch out for jumpscares",
            "the glow of the pumpkins are also powered by pings",
            "not sure what a \"ghost ping\" is but i'm pretty sure that's not my job to deal with",
            "the full moon is actually increasing your luck",
            "awoooo! i mean, uhh, i'm not a werewolf, what's that",
            "creepiest ping of the season right here",
            "i just heard something whisper 'latency...' in the dark",
            "this ping is haunted. click at your own risk",
            "server went trick-or-treating and brought back lag",
            "ghoul got your ping",
            "i pinged and now my mirror's reflecting someone else",
        )
    }

    if (new Date().getMonth() === 11 && new Date().getDate() >= 20) { 
        messagesList.push(
            "i'm feeling pretty jolly today",
            "the holidays are upon us",
            "hang your ornaments",
            "it's beginning to lO*o*k- ugh, sorry, i can't sing",
            "have some pts as a gift this year. don't spend it all in one place",
            "this ping is JOLLY",
            "and we ping in merryment",
            "since i also have to process snow, pings might be slower",
            "careful not to get snow in your eyes while pinging",
            "this ping is gift-wrapped and slightly delayed",
            "under the digital tree... one ping, just for you",
            "deck the halls with packets of latency",
            "ping bells, ping bells, ping all the way~",
            "this ping comes with extra snowflakes",
            "frosty the pingman sends his regards",
            "the server is cold. please warm it with pings",
            "i hung your ping on the tree. hope that's okay",
        )
    }

    //new years
    if (new Date().getMonth() === 0 && new Date().getDate() <= 5) {
        messagesList.push(
            "new year, same ping",
            "resolution: reduce latency (no promises)",
            "hello new year, your ping has arrived",
            "i scheduled this ping a year ago. totally planned",
            "new year, new me. new lag? i hope not",
            "we made it! again! ping goes on",
            "congrats on surviving another revolution! around the sun, i mean",
            "i haven't pinged since last year! haha! actually that's probably not true",
            "the fireworks are scaring the pings away :(",
        )
    }

    // only if player was clicking (can't appear with /ping, only on button press)
    if (context.score) {
        const totalClicks = context.stats.total.clicks;
        if (Math.random() * 100 <= 7) messagesList = [
            `i don't know if i made this clicking too addictive. sorry in advance`,
            `number go up!`,
            `did you know \`1,000,000 pts\` is called a megapt?`,
            `if you keep clicking like this, you'll be the next clicker extraordinaire`,
            "i'm glad it's a button and not a command",
            `hopefully this ping isn't too much to deal with while you click away`,
            `how come you like clicking this so much?`,
            `i mean, i get it, clicking can be fun, but don't you have other things to do? like sleep? eat?`,
            `careful, don't get carpal tunnel`,
            `try putting on some music and clicking to the beat`,
            `what if i turned the button blue, and it was a super ping?`,
            `you know, they say the more you click, the faster your ping gets (not scientifically proven)`,
            `maybe there's a secret ping dimension if you score high enough (but probably not)`,
            `i'm so glad they let you ping eternally`,
            `you're currently #${Math.ceil(Math.random() * 10)} in the world! just kidding, i can't be bothered to check, you can check ${getEmbeddedCommand("leaderboard")} though`,
            `do you actually care about my ping? or do you just want \`pts\`? it's okay, i don't mind`,
            totalClicks >= 100 ? `${totalClicks} is a pretty big amount of pings` : `you've pinged me ${totalClicks} times`,
            totalClicks >= 1000 ? `is the carpal tunnel setting in yet? with your ${totalClicks} pings?` : `you've pinged me ${totalClicks} times`,
            `points and \`pts\` are not the same, do NOT confuse them`,
            `"\`pts\`" is pronounced like "points" but remember they're not the same`,
            `that ping scored you a full \`${context.score} pts\`.`,
            `what if i gave you another \`${context.score * 2} pts\`? you can probably get that by just clicking a bit more`,
            `you got \`${context.score} pts\` just then, which is like, a lot. probably`,
            totalClicks >= 500 ? `you've clicked ${totalClicks} times. is your mouse okay?` : `you've clicked ${totalClicks} times. that's like, medium pinger level`,
            `you've earned \`${context.score} pts\` from this one ping, and not a single one was a tax write-off`,
            `click count: ${totalClicks}. you should probably stretch your fingers`,
            `ping economy in shambles (you clicked too hard)`,
            `you've out-clicked 99.9% of people who never clicked at all. the other 0.1% are, uhh...?`,
            `what if every click made a wish come true?`,
            `clicking this much might cause ping hallucinations`,
            `don't worry, i'm logging all this to your permanent click record`,
            `this button isn't addictive. you're just... very motivated`,
        ]
    }

    if (context.slumberClicks && Math.random() * 100 <= 12) {
        messagesList = [
            `good morning! how was your nap?`,
            `i hope you had a good nap!`,
            `sleep pays off; you have a multiplier now!`,
            `yawn... oh, you're back?`,
            `you've been gone for a while, did you take a nap?`,
            `welcome back from your well-deserved break`,
            `the return of the king... queen... monarch, whatever you are`, // discord.js doesn't have pronoun support :(
            `hey, if you're allowed to sleep, i am too`,
            `i... kind of missed you, not gonna lie`,
            `was it a nap or a side quest?`,
            `you've returned from the shadow realm of inactivity`,
            `nice of you to join us, sleeping beauty`,
            `every break deserves a dramatic re-entry. this is yours`,
            `dreamland lost a traveler, and we gained a clicker`,
            `back from the void with ping in your heart`,
            `i'm very eepy,,`,
            "rise and click, sleepyhead",
            "welcome back from the ping void",
            "look who decided to come back 👀",
            "i was just about to throw a party without you, thank goodness you're back",
            "absence makes the pings grow faster. not the saying, i understand",
            "did i say something wrong? or did you just need to go to bed",
            "and just like that, the slumber ends",
            "i dreamt you came back. then you did. weird",
            "you disappeared like a packet in bad wifi (since those usually reappear later)",
            "welcome back! did you bring snacks?",
            "but here's the eeper",
        ]
    } 

    if (context.glimmerClicks && Math.random() * 100 <= 7) {
        messagesList = [
            `it's still sparkly from last time`,
            `i hope you like sparkles`,
            `it's not blue but it's as close as it gets`,
            `rrRRrr, shiny`,
            `the blue isn't here but the sparkles are`,
            `i'm seeing stars, and not because i've been punched in the face`,
            `the blue ping is gone, but the sparkles remain`,
            `i wonder if the sparkles form a constellation`,
            `i actually ran out of glitter so this is glitter *glue*`,
            `i'm out of blue pings, but i have sparkles`,
            `i'm not sure if this is glitter or just dust`,
            `the sparkles whispered your name`,
            "the sparkles haven't left yet. neither should you",
            "the glitter boosts your score AND looks cool! a win-win",
            "don't worry, it's just residual stardust",
            "ping particles still in the air, careful when inhaling",
            "the sparkles are non-toxic, probably",
            "there's magic in the lagdust",
            "the sparkles are not a metaphor. or maybe they are. i haven't decided yet",
            "the sparkles are fading... unless maybe you keep clicking?",
            "don't eat the glitter. trust me, i've tried",
        ]
    }

    // high ping, almost always shows
    if (ping >= 150 && Math.random() * 100 <= 75) messagesList = [
        `yikes`,
        `big number warning!`,
        `this is how NOT to latency:`,
        `i'm trying my best, why is my ping`,
        `OH NO`,
        `i'm tr-        -est, o-           -ard to focus`,
        `someone save me from`,
        `[Server/WARN] Can't keep up! Is the server overloaded? Running ${Math.round(ping / 20)} ticks behind, or`,
        `it hurts it hurts it hurts`,
        `quick! someone call tech support!`,
        `404 Ping Not Found?`,
        `this is the internet's fault, not mine, right?`,
        `the ping dimension is unstable?`,
        "i accidentally sent the ping by carrier pigeon!",
        "i swear i'm not sleeping on the job!",
        `the ping... got stuck in traffic?`,
        `lag is just... unintentional suspense?`,
        `you can practically hear the dial-up sounds! i swear i'm not on dialup`,
        `it, um, took the scenic route?`,
        `ping is... out for lunch?`,
        `okay, so like, i'm trying my best`,
        `this ping... uhh... made a wrong turn at albuquerque?`,
        `ping... stopped for lunch on the way here?`,
        `slow ping is still ping. right?`,
        `okay, okay, i admit, this is on me`,
        `ping will be here in... about tomorrow? oh no no no...`,
        `the data had to... swim across the ocean?`,
        `i forgot what i was doing!`,
        `i'm here! I'M HERE! I'M... late...`
    ]

    // 15% chance to get a regular flavored ping message, so it's not super uncommon
    if (Math.random() * 100 <= 15) {
        messagesList = [
            "pong :3"
        ]
    }

    // prevents blue messages showing really frequently
    const allowBlueMessages = (context.blueCombo || 0) <= 2 || !context.spawnedSuper || Math.random() * 100 <= 20;

    // blue ping just spawned
    if (context.spawnedSuper && allowBlueMessages) {
        messagesList = [
            `hey, look at that!`,
            `whoa... it's blue now!?`,
            `where did that thing come from`,
            `ooooh, shiny`,
            `the blue might disappear if you don't click it!`,
            `whoa! check it out! a blue thingymabob`,
            "what the blue?!",
            "this is not a drill! blue ping is here",
            "blue means go! or maybe... ping faster?",
            "ping anomaly in sector 4!",
            "shiny ping! catch it!",
            "stay calm! but you do still need to click the blue one",
            "you found the shiny one! quick, click before it vanishes",
            "you don't see that every ping!",
            "don't miss your chance!",
            "you've summoned a ping of great power",
            "it's a blue ping! you know what to do",
            "ping again vs the ping they told you not to worry about",
            "it's practically glowing",
            "do you see that? it's BLUE!",
            "quick! it's blue! click it like your mouse depends on it",
            "there it is! the ping you've been waiting for (maybe)",
            "don't just stand there. it's shiny!!",
            "an anomoly in my calculations! might as well take advantage of it",
            "blue ping detected. i know it's scary, but please try not to scream",
            "it's... so... blue...!",
            "you probably want to click that",
            "blue appearance! it's super effective at looking cool",
        ]
        if (context.artisanNextSymbols) {
            messagesList.push(
                "SIX buttons?! that's just unnecessary",
                "hey look, another row!",
                "they said multiple ping rows couldn't be done!"
            )
        } else {
            messagesList.push(
                "another button appeared!",
                "TWO???",
                "they said two buttons couldn't be done!"
            )
        }
    }

    // blue ping just clicked
    if (context.isSuper && allowBlueMessages) {
        let mult = (15 * (context.blueStrength)).toFixed(2);
        if (context.blueStrength === 1) mult = "15"
        messagesList = [
            `that's a lot of \`pts\`!`,
            "whoa",
            `${mult}x! that's a lot of x! i mean, \`pts\``,
            "isn't RNG just beautiful?",
            "lucky you!",
            `${mult}x \`pts\`?! holy moly!`,
            "RNGesus is smiling upon you",
            "that ping was juiced",
            "this is what ping greatness feels like, i bet",
            "ping results: critical success",
            `super effective! ${mult}x \`pts\`!`,
            "nice shot! jackpot ping confirmed",
            "that was awesome",
            `${mult}x multiplier? you're living the dream`,
            `you just dealt ${mult}x damage to the button. nice`,
            "your click was a direct hit!",
            `that was a ${mult}x ping! i hope your mouse is proud`,
            `${mult}x is like... so many...`,
            `you just got ${mult}x the normal ping. i need to sit down`,
            `that ${mult}x ping could power a small country (for like maybe a second)`,
        ]
        if ((context.blueCombo || 0) > 3) {
            messagesList.push(
                "wow, look at that combo go",
                "do you think if you get enough in a row it'll turn more purple?",
                `${context.blueCombo} in a row is pretty`,
                `${context.blueCombo} blue pings, and it'll only grow from there`,
            )
        }
        if (context.specials.glimmer) {
            messagesList.push(
                "it even burst into little sparkles, too!",
                "the sparkles of that are gonna hang out for a while",
            )
        }
        if (new Date().getMonth() === 5) {
            messagesList.push(
                "this one has blue... erm, is blue and has pronouns",
                `the ${mult}x bonus is from the power of being yourself`,
            )
        }
    }

    // rare messages (0.1% chance)
    if (context.rare) {
        messagesList = [
            "this one is rare. like, really rare. like, 0.1% chance rare. feel proud of yourself",
            "legend says only 0.1% of people see this message. congrats, chosen one",
            "this ping is ultra shiny! screenshot or it didn't happen",
            "you'll never see this message again. or maybe you will. RNG is weird",
            "x100.00 WHOA!",
            "this ping is so rare, it might as well be a unicorn",
            "congratulations! you've unlocked the rarest ping message",
            "this ping is rarer than a shiny Pokémon", // actually i don't think it is but whatever
        ]
    }

    if (context.fromConsole) {
        messagesList = [
            "don't tell anyone, but this is my actual ping",
            "to be honest, i never really believed the pings were that fast",
            "round trip! that means there and back. and this is how fast it was",
            "btw you won't gain pts or stats from this",
            "thanks for actually caring about my ping, it means a lot",
            "aren't you just the nerdiest nerd ever",
            "let me know when you want to go back to pts farming"
        ]
    }

    // bot just restarted
    if (ping === -1) {
        ping = "unknown "
        messagesList = [
            "i'm lost in cyberspace",
            "reality is collapsing, please try again later",
            "milliseconds? more like mystery seconds",
            "ping is sentient, and i *think* is trying to kill me?",
            "ping? what's a ping? where am i? what's happening?",
            "i don't think this is supposed to happen",
            "who needs time when you have mystery?",
            "520 Too Philosophical",
            "ping entered the quantum realm",
            "i'm... awake... i think?",
            "ping is currently on a spiritual journey",
            "we are currently experiencing a reality outage",
            "ping status: existential",
            "this ping defied the laws of time",
            "restart detected. who are you? what are you asking for?",
            "ping is, uh, on another plane of existence right now",
            "reboot complete. reality questionable.",
            "ping lost in the reboot void",
            "bot restarted. ping still recalculating existence",
            "the bot has returned from the abyss. hello again.",
            "ping undefined. consciousness achieved.",
            "after a brief existential crisis, i'm back, kinda",
            "ping is searching for purpose after restart",
            "just woke up from maintenance mode. where am i?",
            "the ping is confused and so am i",
            "ping momentarily became one with the universe",
            "i just woke up. what year is it?",
            "bot rebooted but left its consciousness behind",
            "this ping has no ping.. very paradoxical",
        ]
        if (context.stats.total.eternities > 0) {
            messagesList.push(
                "milliseconds? buddy, we're talking *eternities*... and not the prestige layer",
            )
        } else {
            messagesList.push(
                "milliseconds? buddy, we're talking *eternities*",
            )
        }
    }

    const message = messagesList[Math.floor(Math.random() * messagesList.length)]; // pick a random one and return it

    return `${message} (${ping}ms)`
}

module.exports = get;
